### ISSUE TITLE
Doesn't work with latest npm

### ISSUE THREAD

**Issue by sumproxy** [ewnd9/dictionary-cli#3]
Couldn't make it work with all my effort

**Comment by ewnd9** [comment]
Hi, provide log from npm, please.

**Comment by sumproxy** [comment]
Sure:

```
/Users/SumProxy> .node/lib/node_modules/npm/cli.js install dictionary-cli@1.0.0
npm WARN engine meow@3.3.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine indent-string@1.2.2: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine object-assign@3.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine camelcase-keys@1.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine map-obj@1.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine camelcase@1.2.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine repeating@1.1.3: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine get-stdin@4.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine user-home@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine form-data@1.0.0-rc3: wanted: {"node":">= 0.10"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine tough-cookie@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine har-validator@1.8.0: wanted: {"node":">=0.10"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine is-finite@1.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine os-homedir@1.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine figures@1.3.5: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine chalk@1.1.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-regex@1.1.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine number-is-nan@1.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine chalk@1.1.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine strip-ansi@2.0.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine has-ansi@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-styles@2.1.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine strip-ansi@3.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-styles@2.1.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine has-ansi@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine strip-ansi@3.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-regex@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-regex@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-regex@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
npm WARN engine ansi-regex@2.0.0: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.9","npm":"2.14.1"})
dictionary-cli@1.0.0 node_modules/dictionary-cli
├── bluebird@2.9.34
├── lodash@3.10.1
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)
├── yandex-translate@2.0.2 (request@2.16.6)
├── yandex-dictionary@0.0.0 (request@2.61.0)
└── inquirer-credentials@1.1.0 (dot-file-config@0.4.0, inquirer-bluebird@1.0.2)
```

npm -v:

```
.node/lib/node_modules/npm/cli.js -v
2.14.1
```

dictionary output

```
node_modules/dictionary-cli/cli.js hello
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at /Users/SumProxy/node_modules/dictionary-cli/cli.js:78:17
    at tryCatcher (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/Users/SumProxy/node_modules/dictionary-cli/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
```

**Comment by sumproxy** [comment]
I tried it with several versions of node.js pkg'es on my mac.

**Comment by ewnd9** [comment]
Just uploaded `v1.1.0` to npm, should be fixed now

**Comment by sumproxy** [comment]
Seems to work, thanks
